### PR TITLE
update version for acs -> master

### PR DESCRIPTION
**Pull request by didi9**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/terraform-aws-mobile-gateway-lambda/7)

### CODE REVIEW

**Review by didi9 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/byu-oit/terraform-aws-mobile-gateway-lambda/7)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @romrell4)

*[a discussion](https://reviewable.io/reviews/byu-oit/terraform-aws-mobile-gateway-lambda/7#-MHYbxmE5HkQtIYicLg6:-MHYbxmF0MkAZWXHDuQt:b-5vthlw) (no related file):*
Not sure if this is exactly the reason, but dining-account-lambda-v2 points to this repo, and it's getting an error about terraform version not being able to be used/matching tf_version: '0.13.1' (which is in the ci.yml). Or is there a different reason why that would be occurring?

---

**Review by romrell4 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/byu-oit/terraform-aws-mobile-gateway-lambda/7)* status: all files reviewed, 1 unresolved discussion (waiting on @didi9)

*[a discussion](https://reviewable.io/reviews/byu-oit/terraform-aws-mobile-gateway-lambda/7#-MHZAUBI197S01DjZK1D:-MHZAUBI197S01DjZK1E:bnq88vx) (no related file):*
This looks good. Do you know how to release a new version?

---

**Review by didi9 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/byu-oit/terraform-aws-mobile-gateway-lambda/7)* status: all files reviewed, 1 unresolved discussion (waiting on @romrell4)

*[a discussion](https://reviewable.io/reviews/byu-oit/terraform-aws-mobile-gateway-lambda/7#-MHZAUBI197S01DjZK1D:-MHm6GKD8brQndWIVjgN:b-cr1abw) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This looks good. Do you know how to release a new version?
</blockquote></details>

I don't

---

**Review by romrell4 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/byu-oit/terraform-aws-mobile-gateway-lambda/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
